---
- name: Add MariaDB 10.1 repository (RedHat)
  yum_repository:
    name: MariaDB
    description: MariaDB
    file: mariadb
    baseurl: http://yum.mariadb.org/10.1/centos7-amd64
    gpgcheck: yes
    gpgkey: https://yum.mariadb.org/RPM-GPG-KEY-MariaDB

- name: Install MariaDB (RedHat)
  yum: name={{ item }} state=present
  with_items:
    - MariaDB-server
    - MariaDB-client
  notify:
    - restart mysql
    - enable mysql

- name: Install MySQLdb Python package for secure installations. (RedHat)
  yum: name=MySQL-python state=present
  when: mysql_secure_installation and mysql_root_password is defined
