---
- include: centos.yml
  when: ansible_os_family == "RedHat" and ansible_distribution_major_version|int >= 6
  notify:
    - start mysql
    - enable mysql

- include: ubuntu.yml
  when: ansible_distribution == 'Ubuntu' and ansible_distribution_version == '14.04'

- name: Add configuration
  template: src={{ mysql_conf_tpl }} dest={{ mysql_conf_dir[ansible_distribution] }}/{{ mysql_conf_file }} owner=root group=root mode=0644
  when: mysql_conf_tpl != 'change_me'
  notify:
    - restart mysql
    - enable mysql

- include: mysql_secure_installation.yml
  when: mysql_secure_installation and mysql_root_password is defined
